import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import PartVisual from '../../components/customer/PartVisual'
import { useCart } from '../../contexts/CartContext'
import { formatLKR } from '../../utils/currency'

export default function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart(); const delivery = items.length ? 850 : 0
  return <main className="simple-page"><header className="page-hero compact"><div className="container"><span>YOUR ORDER</span><h1>Shopping Cart</h1><p>{items.length} {items.length === 1 ? 'item' : 'items'} from verified sellers</p></div></header><div className="container cart-layout">{items.length ? <section className="cart-items"><div className="cart-table-head"><span>Product</span><span>Unit price</span><span>Quantity</span><span>Subtotal</span></div>{items.map((item) => <article className="cart-item" key={item.id}><Link to={`/products/${item.id}`} className="cart-product"><PartVisual product={item} /><span><strong>{item.name}</strong><small>{item.seller}</small><em>{item.condition}</em></span></Link><strong>{formatLKR(item.price)}</strong><div className="quantity-control small"><button onClick={() => updateQuantity(item.id, item.quantity - 1)}><Minus /></button><strong>{item.quantity}</strong><button onClick={() => updateQuantity(item.id, item.quantity + 1)}><Plus /></button></div><strong>{formatLKR(item.price * item.quantity)}</strong><button className="remove-item" onClick={() => removeItem(item.id)} aria-label={`Remove ${item.name}`}><Trash2 /></button></article>)}</section> : <section className="empty-state cart-empty"><ShoppingBag /><h2>Your cart is empty</h2><p>Explore the marketplace to find the right part.</p><Link to="/products">Shop Parts</Link></section>}<aside className="order-summary"><h2>Order Summary</h2><dl><div><dt>Subtotal</dt><dd>{formatLKR(subtotal)}</dd></div><div><dt>Delivery</dt><dd>{delivery ? formatLKR(delivery) : '—'}</dd></div><div className="summary-total"><dt>Total</dt><dd>{formatLKR(subtotal + delivery)}</dd></div></dl><Link className={`checkout-button ${!items.length ? 'disabled' : ''}`} to={items.length ? '/checkout' : '/cart'}>Proceed to Checkout</Link><Link className="continue-button" to="/products">← Continue Shopping</Link><p><span>✓</span> Secure checkout through LankaParts</p></aside></div></main>
}
