import { BadgeCheck, ChevronRight, PackageCheck, Search, ShieldCheck, ShoppingBag, Star, Store, Tags, Truck, Wrench } from 'lucide-react'
import { toast } from 'sonner'
import CategoryCard from '../../components/customer/CategoryCard'
import ProductCard from '../../components/customer/ProductCard'
import SectionHeader from '../../components/common/SectionHeader'
import { brands, categories, products } from '../../data/marketplace'
import { useCart } from '../../contexts/CartContext'

export default function HomePage() {
  const { addItem } = useCart()
  const handleAdd = (product) => { addItem(product); toast.success(`${product.name} added to cart`) }
  return <main id="home">
    <section className="hero-section"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">SRI LANKA'S AUTO PARTS MARKETPLACE</span><h1>Find the Right Part<br />for Your Vehicle</h1><p>Search thousands of quality spare parts from verified sellers across Sri Lanka. Match with confidence, order with ease.</p><div className="hero-stats"><div><strong>15K+</strong><span>Parts listed</span></div><div><strong>250+</strong><span>Verified sellers</span></div><div><strong>25</strong><span>Districts covered</span></div></div></div><div className="hero-visual" aria-label="Automotive wheel illustration"><div className="visual-glow"></div><div className="wheel-art"><div className="wheel-rim"><i></i><i></i><i></i><i></i><i></i></div></div><div className="verified-float"><span>✓</span><div><strong>Verified Sellers</strong><small>Buy with confidence</small></div></div></div></div>
      <div className="container search-wrap" id="vehicle-search"><form className="vehicle-search" onSubmit={(event) => { event.preventDefault(); toast.info('Searching compatible parts…') }}><label><span>What part do you need?</span><input aria-label="Spare part" placeholder="e.g. Brake pads" /></label><label><span>Vehicle brand</span><select aria-label="Vehicle brand" defaultValue=""><option value="" disabled>Select brand</option><option>Toyota</option><option>Honda</option><option>Nissan</option></select></label><label><span>Vehicle model</span><select aria-label="Vehicle model" defaultValue=""><option value="" disabled>Select model</option><option>Aqua</option><option>Vitz</option><option>Prius</option></select></label><label><span>Year</span><select aria-label="Year" defaultValue=""><option value="" disabled>Select year</option><option>2015</option><option>2016</option><option>2017</option></select></label><button type="submit"><Search size={20} /> Search Parts</button></form></div>
    </section>
    <section className="section categories-section" id="categories"><div className="container"><SectionHeader eyebrow="BROWSE THE MARKETPLACE" title="Shop by Category" description="Quickly find the parts you need across our most popular categories." action="View all categories" /><div className="categories-grid">{categories.map((category) => <CategoryCard key={category.name} category={category} />)}</div></div></section>
    <section className="section products-section" id="products"><div className="container"><SectionHeader eyebrow="HANDPICKED FOR YOU" title="Featured Products" description="Popular parts from verified sellers, selected for quality and value." action="Browse all parts" /><div className="products-grid">{products.map((product) => <ProductCard key={product.id} product={product} onAdd={handleAdd} />)}</div></div></section>
    <section className="brands-section" id="brands"><div className="container"><SectionHeader eyebrow="FIND YOUR MAKE" title="Popular Vehicle Brands" /><div className="brands-row">{brands.map((brand) => <a href="#products" key={brand}><span>{brand.slice(0, 1)}</span><strong>{brand}</strong></a>)}</div></div></section>
    <section className="section why-section"><div className="container"><SectionHeader eyebrow="WHY CHOOSE US" title="A Better Way to Buy Vehicle Parts" description="Built to make spare-parts shopping clearer, safer, and easier." /><div className="benefit-grid"><article><BadgeCheck /><h3>Verified Sellers</h3><p>Every seller business is reviewed before listing products.</p></article><article><Wrench /><h3>Vehicle Compatibility</h3><p>Find parts matched to your exact vehicle make and model.</p></article><article><ShieldCheck /><h3>Secure Marketplace</h3><p>Transparent orders and trusted seller information.</p></article><article><Tags /><h3>Genuine Information</h3><p>Clear condition, brand, fitment, and stock details.</p></article><article><PackageCheck /><h3>Easy Ordering</h3><p>Simple cart, checkout, and order tracking in one place.</p></article></div></div></section>
    <section className="seller-cta" id="seller"><div className="container seller-card"><div className="seller-icon"><Store size={34} /></div><div><span className="eyebrow">GROW YOUR BUSINESS</span><h2>Sell Vehicle Parts on LankaParts</h2><p>Seller registration is free. Reach customers across Sri Lanka, manage products and orders, and grow through a trusted marketplace.</p><div className="seller-points"><span><Truck size={16} /> Reach islandwide buyers</span><span><ShoppingBag size={16} /> Simple product management</span><span><Star size={16} /> Build your seller reputation</span></div></div><a href="#register">Become a Seller <ChevronRight size={18} /></a></div></section>
  </main>
}
