import { useMemo, useState } from 'react'
import { Grid2X2, List, SlidersHorizontal } from 'lucide-react'
import { toast } from 'sonner'
import ProductCard from '../../components/customer/ProductCard'
import ProductFilters from '../../components/customer/ProductFilters'
import { useCart } from '../../contexts/CartContext'
import { products } from '../../data/marketplace'

const defaults = { search: '', category: '', brand: '', make: '', model: '', year: '', minPrice: '', maxPrice: '', condition: '', availability: '', seller: '', rating: '' }
export default function ProductsPage() {
  const [filters, setFilters] = useState(defaults); const [sort, setSort] = useState('popular'); const [view, setView] = useState('grid'); const [mobileFilters, setMobileFilters] = useState(false); const [page, setPage] = useState(1); const { addItem } = useCart()
  const results = useMemo(() => {
    const filtered = products.filter((p) => (!filters.search || `${p.name} ${p.brand} ${p.vehicle}`.toLowerCase().includes(filters.search.toLowerCase())) && (!filters.category || p.category === filters.category) && (!filters.brand || p.brand.toLowerCase() === filters.brand.toLowerCase()) && (!filters.make || p.vehicle.includes(filters.make)) && (!filters.model || p.vehicle.includes(filters.model)) && (!filters.minPrice || p.price >= Number(filters.minPrice)) && (!filters.maxPrice || p.price <= Number(filters.maxPrice)) && (!filters.condition || p.condition === filters.condition) && (!filters.availability || p.stock > 0) && (!filters.seller || p.seller === filters.seller) && (!filters.rating || p.rating >= Number.parseFloat(filters.rating)))
    return filtered.toSorted((a, b) => sort === 'price-low' ? a.price - b.price : sort === 'price-high' ? b.price - a.price : sort === 'newest' ? a.createdAt - b.createdAt : b.popularity - a.popularity)
  }, [filters, sort])
  const add = (product) => { addItem(product); toast.success(`${product.name} added to cart`) }
  return <main className="market-page"><header className="page-hero"><div className="container"><span>MARKETPLACE</span><h1>Shop Vehicle Parts</h1><p>Browse quality parts from verified sellers across Sri Lanka.</p></div></header><div className="container shop-layout"><ProductFilters filters={filters} setFilters={setFilters} onClear={() => setFilters(defaults)} /><section className="shop-results"><div className="results-toolbar"><div><strong>{results.length} products</strong><span>Matching your search</span></div><button className="mobile-filter-button" onClick={() => setMobileFilters(true)}><SlidersHorizontal /> Filters</button><div className="sort-control"><label>Sort by <select value={sort} onChange={(e) => setSort(e.target.value)}><option value="popular">Popularity</option><option value="newest">Newest</option><option value="price-low">Price: Low to high</option><option value="price-high">Price: High to low</option></select></label><span className="view-toggle"><button className={view === 'grid' ? 'active' : ''} onClick={() => setView('grid')} aria-label="Grid view"><Grid2X2 /></button><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')} aria-label="List view"><List /></button></span></div></div>{results.length ? <div className={`shop-products ${view}`}>{results.map((product) => <ProductCard key={product.id} product={product} onAdd={add} view={view} />)}</div> : <div className="empty-state"><SlidersHorizontal /><h2>No matching parts</h2><p>Try clearing a filter or searching with another term.</p><button onClick={() => setFilters(defaults)}>Clear filters</button></div>}<nav className="pagination" aria-label="Product pages"><button disabled={page === 1} onClick={() => setPage(page - 1)}>←</button>{[1, 2, 3].map((number) => <button key={number} className={page === number ? 'active' : ''} onClick={() => setPage(number)}>{number}</button>)}<span>…</span><button onClick={() => setPage(page + 1)}>12</button><button onClick={() => setPage(page + 1)}>→</button></nav></section></div>{mobileFilters && <div className="filter-overlay" onMouseDown={(e) => e.target === e.currentTarget && setMobileFilters(false)}><ProductFilters mobile filters={filters} setFilters={setFilters} onClose={() => setMobileFilters(false)} onClear={() => setFilters(defaults)} /></div>}</main>
}
