import { Search, X } from 'lucide-react'
import { brands, categories } from '../../data/marketplace'

export default function ProductFilters({ filters, setFilters, mobile, onClose, onClear }) {
  const set = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  return <aside className={`shop-filters ${mobile ? 'mobile-filter-drawer' : ''}`}><div className="filter-heading"><h2>Filters</h2>{mobile && <button onClick={onClose} aria-label="Close filters"><X /></button>}</div><label className="filter-search"><Search /><input value={filters.search} onChange={(e) => set('search', e.target.value)} placeholder="Search parts" /></label><FilterSelect label="Category" value={filters.category} onChange={(v) => set('category', v)} options={categories.map((item) => item.name)} /><FilterSelect label="Brand" value={filters.brand} onChange={(v) => set('brand', v)} options={brands.concat(['NGK', 'KYB', 'Osram', 'Bosch'])} /><FilterSelect label="Vehicle make" value={filters.make} onChange={(v) => set('make', v)} options={brands} /><FilterSelect label="Vehicle model" value={filters.model} onChange={(v) => set('model', v)} options={['Aqua', 'Prius', 'Vitz', 'Fit', 'Wagon R', 'Dayz']} /><FilterSelect label="Year" value={filters.year} onChange={(v) => set('year', v)} options={['2021', '2020', '2018', '2015', '2012', '2010']} /><div className="filter-block"><h3>Price range</h3><div className="price-inputs"><input type="number" value={filters.minPrice} onChange={(e) => set('minPrice', e.target.value)} placeholder="Min LKR" /><span>—</span><input type="number" value={filters.maxPrice} onChange={(e) => set('maxPrice', e.target.value)} placeholder="Max LKR" /></div></div><FilterChecks title="Condition" values={['New', 'Used', 'Reconditioned']} selected={filters.condition} onChange={(v) => set('condition', v)} /><FilterChecks title="Availability" values={['In stock']} selected={filters.availability} onChange={(v) => set('availability', v)} /><FilterSelect label="Seller" value={filters.seller} onChange={(v) => set('seller', v)} options={['AutoZone Lanka', 'Nippon Auto Parts', 'DriveLine Motors', 'Bright Auto Hub']} /><FilterSelect label="Rating" value={filters.rating} onChange={(v) => set('rating', v)} options={['4.5 & up', '4.0 & up']} /><button className="clear-filters" onClick={onClear}>Clear all filters</button>{mobile && <button className="apply-filters" onClick={onClose}>Show results</button>}</aside>
}
function FilterSelect({ label, value, onChange, options }) { return <label className="filter-select"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}><option value="">All {label.toLowerCase()}</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function FilterChecks({ title, values, selected, onChange }) { return <div className="filter-block"><h3>{title}</h3>{values.map((value) => <label className="filter-check" key={value}><input type="checkbox" checked={selected === value} onChange={() => onChange(selected === value ? '' : value)} /> <span>{value}</span></label>)}</div> }
